### PR TITLE
Adding to the catalogue

### PR DESCRIPTION
**Pull request by harvey0908**
I add some new papers to the catalogue and I would like to do a test to ensure the viability of the data firstly.Moreover,I will check the data again in the following work. Please inform me in time if there is any issue.

### CODE REVIEW

**Comment by NickSwainston** [comment]
Thanks for this @harvey0908. Please [allow me to have edit rights](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) (basically just tick the box in the last picture) and I'll start making edits.

**Comment by NickSwainston** [comment]
Looks like the problem is that you have put 0.0 for a large number of the bandwidth values, which will cause errors (can't divide by zero), so basically, the code wasn't able to fit anything. I fixed one of them, so I'll push it once you've given me push permission then you can start working on the rest.

**Comment by NickSwainston** [comment]
I've pushed my changes. I renamed some of the YAML files so make sure to use `pip uninstall pulsar_spectra` to remove the old YAML files

**Comment by harvey0908** [comment]
Thanks,l will try to reconfirm the the bandwidth values.

**Comment by NickSwainston** [comment]
Our current policy is if there are no bandwidth values, do not include that paper (would you agree with this, @cplee1?).

If there are any that you are struggling with, let me know which ones they are, and I'll see if I can at least work out a likely bandwidth.

**Comment by harvey0908** [comment]
Ok,thanks

**Comment by harvey0908** [comment]
As you said,zero as the value of the bandwidth value affects the result.l have reconfirmed it for a part of papers. However, I feel apologetic as a newcomer.It's a little difficult for me to ensure they are correct Including the rest that can't be determined.Can I contact you in other places or leave your email address so that I can contact you in time.

**Comment by NickSwainston** [comment]
There is no need to be apologetic! I am excited that you are the first person to make a pull request of an addition to the catalogue. Because you are the first, it will be difficult as we learn the best way to help newcomers. 

You can continue to message me on this pull request, there is no message limit. If you prefer, you can email me at nickaswainston@gmail.com.

**Comment by harvey0908** [comment]
I have emailed you,including some papers I have confirmed the value of the bandwidth.Sorry to trouble you again.

**Comment by harvey0908** [comment]
Hi ,I noticed you deleted some date. Becauese those flux density measurements from previous publications. Thank you for reminding me , I ignored these situations before. I will check the rest papers.

**Comment by NickSwainston** [comment]
All fixed up and passing all the tests. Thanks again for working with me to get these papers merged!

**Comment by harvey0908** [comment]
OK , Thanks for your help！

**Pull request merged**
